### ISSUE TITLE
add icc-rt to requirements.txt? (same for tbb, likely anyhow better to issue a warning asking the user to install it)

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#129]

**Comment by piotrbartman** [comment]
Need to test it on travis with checking if numba sees icc-rt, on my local machine it doesn't! ($ numba -s)

**Comment by slayoo** [comment]
added execution of ``numba -s`` to .travis.yml (branch used in PR #71):
https://github.com/atmos-cloud-sim-uj/MPyDATA/commit/abdb579f9b1d7dd923e70fdc1e89f685e867b9f3#diff-354f30a63fb0907d4ad57269548329e3

**Comment by slayoo** [comment]
likely better to setup.py as there we can conditionally include dependencies based on the platform used (see setup.py in PyMPDATA): https://github.com/atmos-cloud-sim-uj/PyMPDATA/blob/master/setup.py

**Comment by slayoo** [comment]
let's leave such issues for Numba packagers and Numba documentation creators...
