### ISSUE TITLE
 X = self.size[0] in ICMW setup

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#131]
Does it make any sense???
 
https://github.com/atmos-cloud-sim-uj/PySDM/blob/master/PySDM_examples/ICMW_2012_case_1/setup.py#L83

Shouldn't it be domain span in metres (and not the number of grid elements)

**Comment by slayoo** [comment]
BTW, there seem to be a unit mismatch in the GMD libcloudph++ paper in the relevant eq. (2)

**Comment by piotrbartman** [comment]
self.size is actually the domain span in metres (in contrast to self.grid)

**Comment by slayoo** [comment]
good point!
