### ISSUE TITLE
JOSS submission

### ISSUE THREAD

**Issue by piotrbartman** [atmos-cloud-sim-uj/PySDM#164]
* [x] Consider https://www.pyopensci.org/
* [ ] Find a potential reviewer: https://joss.theoj.org/about#editorial_board
* [x] paper.md (250-1000 words) https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography
  * [x] A list of the authors of the software and their affiliations, using the correct format (see the example).
  * [x] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
  * [x] A clear Statement of Need that illustrates the research purpose of the software.
  * [x] A list of key references, including to other software addressing related needs.
  * [x] Mention an ongoing research projects using the software and recent scholarly publications enabled by it.
  * [x] Acknowledgement of any financial support.
  * [x] paper.bib
* [ ] Documentation
  * [x] README.md
    * [x] Installation instruction
    * [x] Example usage
  * [x] Documentation of core functions
  * [ ] Community guidelines https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines
* [ ] (Optional) create a metadata file https://gist.github.com/arfon/478b2ed49e11f984d6fb
* [x] Checking that your paper compiles: https://whedon.theoj.org/
* [ ] Submit https://joss.theoj.org/papers/new

**Comment by slayoo** [comment]
done!
