### ISSUE TITLE
PyPI distribution

### ISSUE THREAD

**Issue by piotrbartman** [atmos-cloud-sim-uj/PySDM#165]
* [x] Add setup.py https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py
https://packaging.python.org/guides/distributing-packages-using-setuptools/
* [ ] Generating distribution archives: https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives
* [x] Register at PyPI: https://pypi.org
* [ ] Upload distribution: https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives
* [ ] Install `pysdm` package and test it

**Comment by slayoo** [comment]
+ consider obtaining PySDM in colab via pip ? (what to do with examples then?)

**Comment by slayoo** [comment]
all works for us gently now with setup.py in both PySDM and PySDM-examples.
Closing this for now as there seem to be no clear advantage of having it on pypi... but please reopen or open a new issue clarifying that advantage if needed.

**Comment by slayoo** [comment]
we badly need it to be able to simply indicate dependency on PySDM within setup.py.
Currently, with particular commit referenced from within setup.py we are causing trouble for users as, e.g., installation of PySDM-examples causes overwrite of local PySDM install with possibly older PySDM from github

**Comment by slayoo** [comment]
Thanks to @Golui for notifying us of existence of other pysd package on PyPI: https://pypi.org/project/pysdm/
Seems it might be related with this "story": https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

**Comment by slayoo** [comment]
for the record, here's a Github Actions script example that includes a pypi-publish job:
https://github.com/vinecopulib/pyvinecopulib/blob/master/.github/workflows/pypi.yml

**Comment by slayoo** [comment]
v1.4 published on PyPI: https://pypi.org/project/PySDM/

**Comment by slayoo** [comment]
and v1.5 as well, examples as well.
git urls removed from setup.py
