### ISSUE TITLE
examples refactor

### ISSUE THREAD

**Issue by piotrbartman** [atmos-cloud-sim-uj/PySDM#166]
- [x] create box, parcel, kinematic subdirectories and readmes
- [x] move tutorials to MoAC
- [ ] move Box readme from main README.md to box/readme.ipynb
- [x] update TOC with colab/mybinder links in README.md
- [ ] ICMW animation in README.md
- [x] enable diff for all three readme.ipynb in .travis.yml

**Comment by slayoo** [comment]
animation idea is noted in #149
box/readme.ipynb and README.md example will likely differ somehow.
Closing
