### ISSUE TITLE
sort out random OSX segfaults

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#192]
e.g. here: https://travis-ci.org/github/atmos-cloud-sim-uj/PySDM/jobs/721358705

**Comment by slayoo** [comment]
one more: https://travis-ci.org/github/atmos-cloud-sim-uj/PySDM/jobs/723757728

**Comment by piotrbartman** [comment]
apparently fixed by https://github.com/atmos-cloud-sim-uj/PySDM/commit/073bbe7534d11e3e93f36bd1c67ab76bfd961fe6
