### ISSUE TITLE
add git clone in the first cell of example notebooks so all files are accessible on colab

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#21]

**Comment by piotrbartman** [comment]
find out elegant way to do this

**Comment by slayoo** [comment]
almost done, remaining TODOs:
- [ ] make first cell safe for repeated execution (cd, clone, ...)
- [ ] sort out matplotlib error (screenshot below)
- [ ] add colab cells to remaining examples + entries/badges in README

![image](https://user-images.githubusercontent.com/89685/88276687-c4d09a00-ccdf-11ea-8f57-e3b9a3aae18f.png)

**Comment by slayoo** [comment]
the matplotlib error is irreproducible, unclear, and likely not originating from PySDM code. Closing
