### ISSUE TITLE
truncated spectrum sampling

### ISSUE THREAD

**Issue by piotrbartman** [atmos-cloud-sim-uj/PySDM#219]
![image](https://user-images.githubusercontent.com/28824705/94429779-2820f180-0193-11eb-9fcf-8758c1562b2f.png)

**Comment by slayoo** [comment]
https://github.com/atmos-cloud-sim-uj/PySDM/commit/b09ebf4b8470615a143fa5bb0b3d55fa2daf0fce#diff-a15468cf25b9eda6f2393c35d41457f0
?

**Comment by piotrbartman** [comment]
being addresed (incl test) in #221
