### ISSUE TITLE
Remove collection efficiency dependency on mesh size for 0D box setup

### ISSUE THREAD

**Issue by edejong-caltech** [atmos-cloud-sim-uj/PySDM#234]
My feeling is that a 0D/box setup should not require specification of any physical dimension or mesh size. However, in attempting to run such a scenario, an error is thrown in:

`PySDM/core.py in normalize(self, prob, norm_factor, subs)`

`def normalize(self, prob, norm_factor, subs): `
`---> 63         factor = self.dt/subs/self.mesh.dv `

**Comment by slayoo** [comment]
Thank for feedback!
Could you post here the actual code which triggers this exception?

We've put here a minimal example for 0D setup:
https://github.com/atmos-cloud-sim-uj/PySDM/blob/master/PySDM_tutorials/environments/box.ipynb
Does it work for you?

I agree that for condensation there is no need to define dV... but since the coalescence kernel is the rate of collisions per volume, we do need the sample volume, right?

**Comment by slayoo** [comment]
(I guess part of the issue could be that we work here with multiplicities of super droplets, which are extensive...)

**Comment by edejong-caltech** [comment]
Ah, thank you for clarifying @slayoo . I was working under the assumption that the kernel should be in units of collisions per second, rather than collisions per volume per second. It would be nice then if in a 0D setup one could specify either a mesh size and kernel (as in your example), or only a kernel as in my example which breaks:

[https://github.com/edejong-caltech/PySDM/blob/gauss_basis/PySDM_examples/edejong_runs/kernel_units_breaking.ipynb](url)

A function which automatically checks the units on specified dynamics for a given kernel type would be useful in this case.

**Comment by slayoo** [comment]
Hmmm... what I wrote seems wrong, sorry.

Let's look at Shin-ichiro's paper:

![image](https://user-images.githubusercontent.com/89685/96043683-a3f78b00-0e6f-11eb-9c21-978a4f8ec9e7.png)

**Comment by slayoo** [comment]
So, indeed evaluating the probability of collisions we use ΔV, but it's not part of the kernel (sorry!).

**Comment by edejong-caltech** [comment]
Thanks for clarifying, everything is working now 👍  

It would definitely be helpful to note the definition of the kernel's units in future documentation ;)

**Comment by slayoo** [comment]
> A function which automatically checks the units on specified dynamics for a given kernel type would be useful in this case.

This would be tricky as the (sad) truth is that we need to use the FakeUnitRegistry everywhere besides the unit tests of physical formulae.

**Comment by slayoo** [comment]
see https://github.com/atmos-cloud-sim-uj/PySDM/blob/master/PySDM/physics/_fake_unit_registry.py

**Comment by slayoo** [comment]
a bit simpler than https://github.com/igfuw/libcloudphxx/blob/master/include/libcloudph%2B%2B/common/detail/fake_units.hpp
;)

**Comment by slayoo** [comment]
With #235 merged, the error message in your example is now:
```
---> 15 builder.set_environment(Box(dt=1 * si.s))

TypeError: __init__() missing 1 required positional argument: 'dv'
```
