### ISSUE TITLE
Finalize backends

### ISSUE THREAD

**Issue by tehAgitto** [atmos-cloud-sim-uj/PySDM#246]
# _maths_methods
| | Numba | ThrustRTC
|:---:|:---:|:---:|
| add | &check; | &check; | 
| row_modulo| &check; | &check; | 
| floor| &check; | &check; | 
| floor_out_of_place|&check; | &check; | 
| multiply| &check; | &check; | 
| multiply_out_of_place|&check; | &check; | 
| power|&check; | &check; | 
| subtract| &check; | &check; | 
| urand|&check; | &check; | 

# _algorithmic_methods
| | Numba | ThrustRTC |
|:---:|:---:|:---:|
| calculate_displacement | &check; | &check; | 
| coalescence| &check; | &check; | 
| condensation| &check; | &cross; |
|flag_precipitated | &check; | &check; | 
| linear_collection_efficiency| &check; | &check; | 
| interpolation| &check; | &check; | 
| make_cell_caretaker| &check; | &check; | 
| moments | &check; |  &cross; &#x1f41e; | 
| normalize| &check; | &check; | 
| remove_zeros| &check; | &check; | 

# _algorithmic__step_methods
| | Numba | ThrustRTC |
|:---:|:---:|:---:|
| amax | &check; | &check; | 
| amin | &check; | &check; | 
| cell_id | &check; | &check; | 
| distance_pair | &check; | &check; | 
| find_pairs | &check; | &check; | 
| max_pair | &check; | &check; |
| sort_pair | &check; | &check; | 
| sum_pair | &check; | &check; | 

# _phisics_methods
| | Numba | ThrustRTC |
|:---:|:---:|:---:|
| explicit_in_space | &check; | &check; | 
| implicit_in_space| &check; | &check; | 
| temperature_pressure_RH| &check; | &check; | 
| radius| &check; | &cross; | 
| dr_dt_MM| &check; | &cross; | 
| dr_dt_FF| &check; | &cross;| 
| dthd_dt| &check; | &cross; | 

# _storage_methods
| | Numba | ThrustRTC | 
|:---:|:---:|:---:|
| array| &check; | &check; | 
| download | &check; | &check; | 
| upload| &check; | &check; | 
| from_ndarray | &check; | &check; | 
| to_ndarray| &check; | &check; | 
| range | &check; | &check; | 
| read_row | &check; | &check; | 
| write_row| &check; | &check; | 
| shuffle_global | &check; | &cross; | 
| shuffle_local| &check; | &check; | 

# condensation_methods
| | Numba | ThrustRTC |
|:---:|:---:|:---:|
| make_adapt_substeps| &check; | &cross; | 
| make_step_fake| &check; | &cross; | 
| make_step| &check; | &cross; | 
| make_step_impl| &check; | &cross; | 
| make_calculate_ml_old| &check; | &cross; | 
| make_calculate_ml_new| &check; | &cross; | 
| make_condensation_solver| &check; | &cross; | 

&#x1f41e; - kludge using numba

**Comment by slayoo** [comment]
thanks!

**Comment by tehAgitto** [comment]
Unfortunately adding interactive checkbox in markdown table doesn't work at all :(

**Comment by slayoo** [comment]
we're almost there! Closing as the table above is outdated and there are separate issues for missing features
