### ISSUE TITLE
add .gitignore

### ISSUE THREAD

**Issue by tehAgitto** [atmos-cloud-sim-uj/PySDM#283]
pycharm is creating many not necessary files, so we need to ignore them.

We need permission (@tehAgitto @Kyetuur) to create a pull request @slayoo

**Comment by slayoo** [comment]
@tehAgitto @Kyetuur For sure, anyone can create a pull request! If there is any problem with it, please report.

Re .gitignore, I'm hesitant as each developer might have its own set of things to ignore (PySDM is not requireing or even suggesting to use PyCharm).

Quoting git docs (https://git-scm.com/docs/gitignore):
> Patterns which are specific to a particular repository but which do not need to be shared with other related repositories (e.g., auxiliary files that live inside the repository but are specific to one user’s workflow) should go into the $GIT_DIR/info/exclude file.

So perhaps in the case of PyCharm files it's better to use .git/info/exclude locally?

Thanks!

**Comment by tehAgitto** [comment]
about PR - I had some env issues.
In my honest opinion every person using PyCharm want to ignore files such as __pycache__ or .idea\ folder. 
stated in the same doc:

``Patterns which should be version-controlled and distributed to other repositories via clone (i.e., files that all developers will want to ignore) should go into a .gitignore file.``

I just cannot find the case when one developer wants to push these files.

**Comment by tehAgitto** [comment]
At least we can take into account __pycache__ folders as it is done in the official [gitignore/Python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore)

**Comment by slayoo** [comment]
To be clear, "I'm hesitant" does not mean I'm against :)!
While PyCharm does not suggest to add/commit cache or .idea files, it does so for Jupyter checkpointing stuff, and this is indeed worth adding to .gitignore as suggested in the Github's example files:
https://github.com/github/gitignore/blob/master/Python.gitignore#L79

So, let's simply use the Github's file!
Here it is:https://github.com/atmos-cloud-sim-uj/PySDM/commit/768e482298d440a3e1e0f39c1b8df6a9d0fb10a2
Thanks!
