### ISSUE TITLE
Condensation.substeps initial value

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#291]
Currently, the initial value for Condensation.substeps is set with this statement (https://github.com/slayoo/PySDM/blob/warnings/PySDM/dynamics/condensation.py#L39):

```python
        self.substeps[:] = int(np.maximum(1, int(self.core.dt)))  # TODO: min substep length
```

core.dt is often subsecond, hence substeps is set to zero.

This leads to multiple warnings in the logs (e.g., https://ci.appveyor.com/project/slayoo/pysdm/builds/36310294/job/e5ed55forlku9uyt):

```
PySDM_examples\Bartman_2020_MasterThesis\fig_5_BDF_VS_ADAPTIVE.py:27: in data
    results = simulation.run()
PySDM_examples\Arabas_and_Shima_2017_Fig_5\simulation.py:70: in run
    self.core.run(self.n_substeps)
PySDM\core.py:104: in run
    observer.notify()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <PySDM.products.dynamics.condensation.condensation_timestep.CondensationTimestep object at 0x14742628>
    def notify(self):
        self.download_to_buffer(self.condensation.substeps)
        self.count[:] += self.buffer
>       self.buffer[:] = self.condensation.core.dt / self.buffer
E       RuntimeWarning: divide by zero encountered in true_divide
PySDM\products\dynamics\condensation\condensation_timestep.py:51: RuntimeWarning
```

Besides using ``int(dt)`` being fishy, there seem to also be a unit mismatch - substeps is a dimensionless number of substeps per major time step, while dt is in seconds.

@piotrbartman any thoughts?

**Comment by piotrbartman** [comment]
> core.dt is often subsecond, hence substeps is set to zero.

it impossible to set substeps to 0, there are maximum, not minimum.
This line is equivalent to:
```Python
if dt < 1 * si.s:
    sub_dt = dt
else:
    sub_dt = 1 * si.s \
                  + (dt % 1) / dt  # extra part since substeps are int
```
but of course we operate on number of substeps not on length of substeps.

**Comment by slayoo** [comment]
> it impossible to set substeps to 0, there are maximum, not minimum.

Thank you! The problem causing the warning was actually in the BDF solver where we had zeros returned! 

Regarding substeps initial setting, let's come back to it when working on the examples
