### ISSUE TITLE
moments: averaging with different weight than number (e.g. mass as requested for pH)

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#448]

**Comment by slayoo** [comment]
this could fix the discrepancy in J&P fig 2.
original:
![image](https://user-images.githubusercontent.com/89685/119943172-f61a9600-bf92-11eb-9c83-7ca6cccc156f.png)
PySDM:
![image](https://user-images.githubusercontent.com/89685/119943253-121e3780-bf93-11eb-9525-c987eb4ad3a4.png)

@trontrytel let's try to fix it (pH averaging) on Mon

**Comment by trontrytel** [comment]
copy!
