### ISSUE TITLE
checking constants

### ISSUE THREAD

**Issue by trontrytel** [atmos-cloud-sim-uj/PySDM#525]
https://github.com/atmos-cloud-sim-uj/PySDM/blob/fb619fa842ea419f6f038c532f07432f310f7e7a/PySDM/physics/aqueous_chemistry/support.py#L109

I'm not sure because of the comment left above this line, but shouldn't the value be `7.5 * 1e7`?

**Comment by trontrytel** [comment]
Also, not sure if I understand correctly the table 4 in Kreidenweis. But in libcloudph++, I think, for both dissolution and dissociation of HNO3 I was taking `8700` as the exponent factor. In PySDM its `0` right now.

https://github.com/atmos-cloud-sim-uj/PySDM/blob/fb619fa842ea419f6f038c532f07432f310f7e7a/PySDM/physics/aqueous_chemistry/support.py#L32

https://github.com/atmos-cloud-sim-uj/PySDM/blob/fb619fa842ea419f6f038c532f07432f310f7e7a/PySDM/physics/aqueous_chemistry/support.py#L45

**Comment by slayoo** [comment]
Aniu! I have just rerun the fig 3 J&P example, not a hint of difference in results :(

**Comment by slayoo** [comment]
and Fig 1 (K et al. example) looks as follows:
![image](https://user-images.githubusercontent.com/89685/118882625-ab46b180-b8f4-11eb-93d5-9f19dbed18f4.png)
at least, here there is some "response" to the changed constants

**Comment by slayoo** [comment]
k3 addressed in #538 
Currently the plot looks well!
![image](https://user-images.githubusercontent.com/89685/119898487-356cc680-bf42-11eb-81b0-7f9888afb5c6.png)

**Comment by trontrytel** [comment]
Sounds good. Now we only have to convince ourselves that the way we treat Henrys law is correct...

**Comment by slayoo** [comment]
![image](https://user-images.githubusercontent.com/89685/119899715-c7c19a00-bf43-11eb-82f9-c425b4530fca.png)
:)

**Comment by trontrytel** [comment]
Very cool!

**Comment by slayoo** [comment]
the other two constants are now also changes in #538 
Closing!
