### ISSUE TITLE
ThrustRTC internal error in new algorithmic_method kernel

### ISSUE THREAD

**Issue by edejong-caltech** [atmos-cloud-sim-uj/PySDM#541]
@slayoo  @trontrytel 
In my quest to implement a breakup-like process in PySDM, I am encountering an error for the kernel launch for my new random fragmentation backend algorithmic method. Please see the branch at [https://github.com/edejong-caltech/PySDM/tree/SLAMS-fragmentation](url) with a minimum not-working-example in [https://github.com/edejong-caltech/PySDM/blob/SLAMS-fragmentation/PySDM_tests/breakup_tests/gpu_issue.ipynb](url). 

In this implementation, breakup proceeds similarly to coalescence but takes an additional argument, `n_fragments` to scale the multiplicities and attributes. The breakup process returns expected output when `n_fragments` is returned deterministically, but I have added an additional method to `_algorithmic_methods.py` and additional random generator case that returns only a vector to allow for stochastic fragmentation. 

The Numba and FakeThrust backend for the new method `SLAMS_fragmentation` execute and produce expected output, but the kernel launch for the ThrustRTC backend produces an error: `an internal error happend` (screenshot included). I have not been able to trace the source of the argument error to `launch_n` that is leading to this internal error as the call `n_for_launch_n` does not exist in a readable form within the ThrustRTC library.

<img width="1319" alt="Screen Shot 2021-05-28 at 2 53 19 PM" src="https://user-images.githubusercontent.com/61925387/120045788-a86b5100-bfc5-11eb-8e8f-5a4f007509c4.png">

Here are the current package versions loaded in my environment:
_libgcc_mutex             0.1                        main  
argon2-cffi               20.1.0           py38h27cfd23_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
ca-certificates           2021.4.13            h06a4308_1  
certifi                   2020.12.5        py38h06a4308_0  
cffi                      1.14.5           py38h261ae71_0  
cycler                    0.10.0                   py38_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 5.0.6              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
entrypoints               0.3                      py38_0  
expat                     2.3.0                h2531618_2  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.68.1               h36276a3_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
importlib-metadata        3.10.0           py38h06a4308_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
intel-openmp              2021.2.0           h06a4308_610  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.22.0           py38hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jedi                      0.17.0                   py38_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_core              4.7.1            py38h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
kiwisolver                1.3.1            py38h2531618_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.3                h2531618_0  
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.3.4            py38h06a4308_0  
matplotlib-base           3.3.4            py38h62a2d02_0  
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py38h27cfd23_1  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.1            py38ha9443f7_2  
nb_conda_kernels          2.3.1            py38h06a4308_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
notebook                  6.3.0            py38h06a4308_0  
numpy                     1.20.1           py38h93e21f0_0  
numpy-base                1.20.1           py38h7d8b39e_0  
olefile                   0.46                       py_0  
openssl                   1.1.1k               h27cfd23_0  
packaging                 20.9               pyhd3eb1b0_0  
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.4.3            py38h06a4308_1  
parso                     0.8.2              pyhd3eb1b0_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.2.0            py38he98fc37_0  
pip                       21.0.1           py38h06a4308_0  
prometheus_client         0.10.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycparser                 2.20                       py_2  
pygments                  2.8.1              pyhd3eb1b0_0  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.17.3           py38h7b6447c_0  
pysdm                     1.4.dev194+gb653e8e.d20210517           dev_0    <develop>
python                    3.8.8                hdb3f193_5  
python-dateutil           2.8.1              pyhd3eb1b0_0  
pyzmq                     20.0.0           py38h2531618_1  
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
scipy                     1.6.2            py38had2a1c9_1  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py38h06a4308_0  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.35.4               hdfb4753_0  
tbb                       2021.2.0                 pypi_0    pypi
terminado                 0.9.4            py38h06a4308_0  
testpath                  0.4.4              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
tornado                   6.1              py38h27cfd23_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0

**Comment by slayoo** [comment]
Thanks for reporting, and super happy to hear about these developments!
Could you try if setting NUMBA_DISABLE_JIT=1 env var when launching with FakeThrust triggers any error messages?
(FakeThrust by default uses Numba internally, so errors like array out-of-bounds access are not reported, but after disabling JIT we get basic Python execution and then any such errors in the GPU C code should be reported)

**Comment by slayoo** [comment]
@edejong-caltech I've just tried it locally... and it seems to work:
![image](https://user-images.githubusercontent.com/89685/120247690-a8dd4380-c274-11eb-875f-67e779a50325.png)

**Comment by slayoo** [comment]
perhaps this fix recently commited to master makes it work?
https://github.com/atmos-cloud-sim-uj/PySDM/commit/648137c2a4ee5254266cec9d04dd175c099721c1#diff-26e1f1e51544c7e104d69f5d2b285a480930a56ded22d96151865301d58bf613

**Comment by edejong-caltech** [comment]
Thanks @slayoo. Testing with NUMBA_DISABLE_JIT=1 yielded no errors for me either; merging all recent commits to PySDM master also did not fix the issue when running with GPU backend. I will try running it on Google CoLab later today instead of the Caltech cluster to see if I have the same error. Could it be something with CUDA checking for warp divergence?

**Comment by edejong-caltech** [comment]
Running the code on a Google CoLab GPU leads to the same error:

![Screen Shot 2021-06-01 at 12 50 07 PM](https://user-images.githubusercontent.com/61925387/120382034-08b90600-c2d8-11eb-96fd-e4a5b5843041.png)

**Comment by slayoo** [comment]
One more idea: is it possible that `len(n_fragment)==0`? Apparently ThrustRTC reacts to zero-length launch_n() calls by raising a SystemError with "An internal error happened" message (I guess worth reporting as an issue there). FakeThrust does nothing in such case, so this would explain the difference in behaviour.

**Comment by slayoo** [comment]
One more idea: is it possible that `len(n_fragment)==0`? Apparently ThrustRTC reacts to zero-length launch_n() calls by raising a SystemError with "An internal error happened" message (I guess worth reporting as an issue there). FakeThrust does nothing in such case, so this would explain the difference in behaviour.

**Comment by edejong-caltech** [comment]
Just checked again to confirm, and it is not; the issue persists if I use more pairs such that `len(n_fragment) > 1` as well. Can you point me to the source code for the call `native.n_for_launch_n`? I've been unable to find it to help trace the bug.

**Comment by edejong-caltech** [comment]
I have solved the problem: it was not an argument error but an error with the syntax of the operations in the kernel. A few changes needed to occur:

- Created temporary float for each addition and split operations; ThrustRTC does not allow multiple operations per line.
- Syntax for power changed to `^` rather than `**`
- ThrustRTC does not support negative powers; changed to `tmp = 1 / tmp`
- Also does not support float powers, but does allow fractional powers; changed `^(1.56)` to `^(39/25)`

You can see the modified kernel in the most recent commit to the branch: [https://github.com/edejong-caltech/PySDM/tree/SLAMS-fragmentation](https://github.com/edejong-caltech/PySDM/tree/SLAMS-fragmentation)

I can open an issue with ThrustRTC to provide more detailed internal error feedback for these instances. It may be useful to update FakeThrust to catch these kernel errors.

**Comment by slayoo** [comment]
Thank Emily, this seems relevant:
https://github.com/fynv/ThrustRTC/blob/e1f8a548ed80049c15b2820bd195e1b209ceb670/internal/impl_context.inl#L660

**Comment by slayoo** [comment]
Great!

> I can open an issue with ThrustRTC to provide more detailed internal error feedback for these instances

This would great (also to show there are more users! :))
> I can open an issue with ThrustRTC to provide more detailed internal error feedback for these instances. It may be useful to update FakeThrust to catch these kernel errors.

Definitely!

> ^(39/25)

I'm worried there is an int cast in C++ here?

**Comment by slayoo** [comment]
> Syntax for power changed to ^ rather than **

In C++ ^ will be a bitwise XOR - pow(a, b) should do.

**Comment by edejong-caltech** [comment]
I see that, thank you. It turns out there was also a typecast error; there is no automatic conversion from ints to floats. With that issue resolved, I am able to recombine all the operations into a single line of code. Thanks for your help!
