### ISSUE TITLE
rho missing in advector definition in Shipway & Hill example

### ISSUE THREAD

**Issue by rlhycd** [atmos-cloud-sim-uj/PySDM#542]
https://github.com/atmos-cloud-sim-uj/PySDM-examples/blob/8c644524a8a392e56a9bec4d5abb9ad1c70a4c00/PySDM_examples/Shipway_and_Hill_2012/simulation.py#L23

**Comment by slayoo** [comment]
addressed in: https://github.com/atmos-cloud-sim-uj/PySDM-examples/pull/45
