### ISSUE TITLE
clean up field_values logic in mpdata/arakawa_c (currently it is np.full(np.full(...)))

### ISSUE THREAD

**Issue by abulenok** [atmos-cloud-sim-uj/PySDM#551]
https://github.com/atmos-cloud-sim-uj/PySDM-examples/blob/5e09fcc4c4ed2651bf092827d30d4fa47e4e12a0/PySDM_examples/Arabas_et_al_2015/mpdata.py#L45

https://github.com/atmos-cloud-sim-uj/PySDM/blob/ab6726a6ca60713a7e95b3adc1589845fbba07c8/PySDM/state/arakawa_c.py#L9

**Comment by slayoo** [comment]
this was addressed some time ago, and the file in question is now 16-line log and does not feature a single np.full call
