### ISSUE TITLE
toss_pairs improvement plan

### ISSUE THREAD

**Issue by piotrbartman** [atmos-cloud-sim-uj/PySDM#62]
- [ ] understand what numba's prange does (i.e., when sync happens?)
- [x] replace current sort_by_cell_id with something around a parallel counting sort
- [x] do unsort per segment (like in Shima, per-segment parallelism) - would include find_pairs?
- [ ] try some parallelism within segment 
- [ ] some custom thread-pool logic for find_pairs (as well as condensation!)?

**Comment by slayoo** [comment]
two comments from a duplicate issue (#16):
- https://arxiv.org/abs/1508.03167
- ... and then perhaps a PR to libcloudph++?

**Comment by slayoo** [comment]
Regarding thread-pool logic, perhaps we could try joblib:
https://joblib.readthedocs.io/en/latest/parallel.html#reusing-a-pool-of-workers
