### ISSUE TITLE
Expose parameters to compressed film models

### ISSUE THREAD

**Issue by claresinger** [atmos-cloud-sim-uj/PySDM#629]
It would be nice to have default parameter values for the compressed film model (`delta_min` and `sgm_org`), but to also expose these to the user so that they can be changed from the experiment notebooks. 

Would the way to do this be to add an `__init__` method?

**Comment by slayoo** [comment]
here it is: 
- https://github.com/atmos-cloud-sim-uj/PySDM/pull/631
- https://github.com/atmos-cloud-sim-uj/PySDM-examples/pull/68

usage looks like this:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/89685/134233094-47154c03-5b3c-4174-b553-a99a901f734b.png">

and implementation:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/89685/134233212-f156c8c2-8f1e-4221-879b-e7f04ad8d3da.png">
