### ISSUE TITLE
VTK output stopped working in the 2D kinematic GUI notebook

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#669]
@abulenok let's try to debug it together some day

**Comment by slayoo** [comment]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/89685/140084300-20e32f17-3db8-4853-80df-30ee43bf2df4.png">

**Comment by slayoo** [comment]
selecting the VTK output checkbox causes the simulation to crash after getting through the initialisation

**Comment by abulenok** [comment]
I'm in :)
