### ISSUE TITLE
Add JOSS v2 branch

### ISSUE THREAD

**Issue by edejong-caltech** [atmos-cloud-sim-uj/PySDM#745]

**Comment by slayoo** [comment]
scope:
- [ ] breakup (with Bieli et al. & SLAMS examples) -> EDJ & BMK
- [ ] Abdul-Razzak & Ghan example -> ID & AJ
- [ ] Szuszkowski-Langmuir, kappa vs. insoluble etc -> CS & RW
- [ ] sampling & coalescence (Unterstrasser example) -> AJ & SA
- [ ] immersion freezing (Knopf & Alpert example) -> SA

**Comment by slayoo** [comment]
also, worth considering posting on arXiv or alike

**Comment by slayoo** [comment]
branch created, I guess we do not need this issue anymore, let's just track TODOs within the paper.md on JOSSv2 branch
