### ISSUE TITLE
cancel GitHub actions

### ISSUE THREAD

**Issue by claresinger** [atmos-cloud-sim-uj/PySDM#778]
Maybe we should add this to the workflows to cancel the actions on all but the latest push to a given branch? https://github.com/marketplace/actions/cancel-workflow-action

**Comment by slayoo** [comment]
Thank you @claresinger 
Definitely!
Here's a first try: https://github.com/atmos-cloud-sim-uj/PySDM/pull/780

**Comment by claresinger** [comment]
Great! And let's add it to PySDM-examples too!

**Comment by slayoo** [comment]
https://github.com/atmos-cloud-sim-uj/PySDM-examples/commit/e143bf988ffb7aa65b089c6a6094b6c28acab384

**Comment by slayoo** [comment]
Please confirm if you notice an instance where it actually has worked for you

**Comment by claresinger** [comment]
I don't think this is working yet. Maybe we have this issue where the queue is full? https://github.com/marketplace/actions/cancel-workflow-action#advanced-all-but-latest

**Comment by slayoo** [comment]
commited to main branches on both PySDM and PySDM-examples repos: https://github.com/atmos-cloud-sim-uj/PySDM/commit/ba1eafb4370c931bfb8339bbfb169d284e3c6d92, https://github.com/atmos-cloud-sim-uj/PySDM-examples/commit/a578e2c478704283f7e7041c1054db935a698223 
Please confirm if that helps

**Comment by slayoo** [comment]
would also be great to find a similar solution for Appveyor (which we depend on for 32-bit builds, which IIUC are not supported on GA, and which have helped us resolve issues that Windows users where facing with their 32-bit Python installations which seem to be still not only not unheard of, but even recommended as of 2022: https://docs.microsoft.com/en-us/visualstudio/python/installing-python-interpreters)

**Comment by slayoo** [comment]
well, seems to work, so closing
Thank you, Clare!
