### ISSUE TITLE
add kappa calculations to PySDM

### ISSUE THREAD

**Issue by claresinger** [atmos-cloud-sim-uj/PySDM#789]
Move kappa calculations from individual PySDM examples (e.g. [Lowe example](https://github.com/atmos-cloud-sim-uj/PySDM-examples/blob/main/PySDM_examples/Lowe_et_al_2019/aerosol.py)) to [PySDM initialisation](https://github.com/atmos-cloud-sim-uj/PySDM/tree/master/PySDM/initialisation)

**Comment by claresinger** [comment]
addressed by PR #821

**Comment by slayoo** [comment]
Thank you, Clare!
