### ISSUE TITLE
surface tension examples

### ISSUE THREAD

**Issue by claresinger** [atmos-cloud-sim-uj/PySDM#834]
Merge first version of an ultimate "Singer & Ward 202X" example that shows how all 4 surface tension models can be used. Include aerosol specification and notebook that generates the Köhler curve figure for the JOSS v2 paper.

**Comment by slayoo** [comment]
:rocket:

**Comment by claresinger** [comment]
See https://github.com/atmos-cloud-sim-uj/PySDM-examples/pull/152
