### ISSUE TITLE
finish writing JOSS v2 paper

### ISSUE THREAD

**Issue by claresinger** [atmos-cloud-sim-uj/PySDM#835]

**Comment by slayoo** [comment]
- [ ] update https://github.com/atmos-cloud-sim-uj/PySDM/blob/main/.github/workflows/joss.yml

**Comment by edejong-caltech** [comment]
<img width="708" alt="Screen Shot 2022-05-11 at 11 20 40 AM" src="https://user-images.githubusercontent.com/61925387/167919197-356dde45-8db4-44e5-813f-43a816aa915c.png">
Wondering if we should reduce the amount of discussion currently given to enhanced API?

**Comment by slayoo** [comment]
We are just covering additions to the API, and merely exemplifying them, not documenting. We have auto-generated API docs, so I think everything is in line with JOSS guidelines
