### ISSUE TITLE
Wrong ParticleSizeSpectrumPerVolume computation in Shipway and Hill example

### ISSUE THREAD

**Issue by sajjadazimi** [atmos-cloud-sim-uj/PySDM#840]
**Description**:
The output for 2d products, dry spectrum and wet spectrum, are wrong. I see an array with mixed 1e+16 and 0 elements.
**How to reproduce**:
Initialize both dry spectrum and wet spectrum in the run() function by:
```
output = {}
for k, v in self.particulator.products.items():
        if len(v.shape) == 1:
               output[k] = np.zeros((mesh.grid[-1], nt + 1))
        elif len(v.shape) == 2:
               output[k] = np.zeros((mesh.grid[-1], 100, nt + 1))
```
and save the output for the 2d products by using the condition:
```
if len(v.shape) == 1:
       output[k][:, step] = v.get()
elif len(v.shape) == 2:
        output[k][:, :, step] = v.get()
         #print(v.get().max())
```
in the save function. Then look at elements in the section
```
output['rhow=2.0_p=True']['wet spectrum'][50,:,100]
```
as an example or print out the maximum at each iteration.

**Comment by slayoo** [comment]
I've used the following version of save_spectrup:
```python
    def save_spectrum(self, index):
        for k, v in self.particulator.products.items():
            if len(v.shape) == 2:
                self.output_products[k][:, :, index] = v.get()  # TODO #840
                print("plotting", k, '...')
                from matplotlib import pyplot
                from matplotlib.colors import LogNorm
                pyplot.title(k)
                pyplot.imshow(self.output_products[k][:, :, index], norm=LogNorm())
                pyplot.xlabel('radius bin index')
                pyplot.ylabel('height bin index')
                pyplot.show()
```
16 sd per cell, no other changes (wrt your PR) and here are the plots:

![Screenshot from 2022-05-16 16-22-43](https://user-images.githubusercontent.com/89685/168684799-079d5f03-c6a0-4076-a09d-164c139feae8.png)

It seems ok?
However, I've noticed that the radius ranges for dry and wet spectra are set to the same values, and this is likely worth changing as the dry aerosol spectra will contain mostly zeros with the binning going up to 100 um.

**Comment by slayoo** [comment]
Ah! Got where the issue comes from: the unit of `ParticleSizeSpectrumPerVolume` is 1/m^4 as this is the spectral density - divided by the bin width (and the bin width is of the order of 1e-8 m).

See here: https://github.com/atmos-cloud-sim-uj/PySDM/blob/a27c3b27987f312952b5dfd84cf469e7b5c37cf1/PySDM/products/size_spectral/particle_size_spectrum.py#L53

**Comment by sajjadazimi** [comment]
Ah yes that's the reason!
I saw numbers like 1 over machine precision and the first thing that came to my mind was that it should be an error. But you're right I missed the other normalization factor.
Then the method works fine and there is no issue. You can close the issue, and I'll finish PR#156.

**Comment by slayoo** [comment]
thanks!
