### ISSUE TITLE
Make breakup dynamic robust and predictable execution time

### ISSUE THREAD

**Issue by edejong-caltech** [atmos-cloud-sim-uj/PySDM#874]
- [ ] Specify which attribute refers to particle volume/mass
- [ ] Build fragmentation size limiters into the break_up dynamic, not fragmentation functions: nf_max (optional, specified), vmax (physical), vmin (specified)
- [ ] Remove internal time substepping so that only a single breakup with max possible gamma is computed
- [ ] Write tests!

**Comment by slayoo** [comment]
@edejong-caltech shall we consider this one as ready to be closed?

**Comment by slayoo** [comment]
IIUC, this is all done. Closing. @edejong-caltech, please reopen, if needed.
