### ISSUE TITLE
Missing parentheses ?

### ISSUE THREAD

**Issue by abulenok** [atmos-cloud-sim-uj/PySDM#932]
In this line `CW[i]` is raised to the power 1
https://github.com/atmos-cloud-sim-uj/PySDM/blob/81b3b43b2c0b15fe23bd5a2bed4f0bb59ba6dcc2/PySDM/backends/impl_numba/methods/collisions_methods.py#L294

**Comment by slayoo** [comment]
clearly.
Thanks, @abulenok !
Here's a PR fixing it: https://github.com/atmos-cloud-sim-uj/PySDM/pull/934
