### ISSUE TITLE
formulae unit test missing an assert statement

### ISSUE THREAD

**Issue by douglowe** [atmos-cloud-sim-uj/PySDM#995]
The function `test_tricker_formula_vectorised` inside the `unit_tests/test_formulae.py` script needs an assert statement.

**Comment by slayoo** [comment]
thank you for reporting! the aim of this test is to check if Numba compilation and vectorisation (or numpy vectorisation for NUMBA_DISABLE_JIT set) does not fail, which is why it was left without an assert, but of course we could add an assert for the output values just for clarity

**Comment by douglowe** [comment]
Ahh - that makes sense.

Probably best to leave out an assert statement then, as the output is not the focus of the test. Instead it might be better to add a comment after the assert comment instead, to note the intent of the test.
